HYPERKVASIR = './datasets/hyper-kvasir/'

ABNORMALITY_DATASET = './datasets/abnormality_dataset/'
ABNORMALITY_TRAIN = './datasets/abnormality_train/'
ABNORMALITY_TEST = './datasets/abnormality_test/'
ABNORMALITY_LABELS = './labels/abnormality_labels.txt'
ABNORMALITY_MODELS = './models/classifiers/abnormalities/'
ABNORMALITY_GANS = './models/gans/abnormalities/'

CONDITION_DATASET = './datasets/condition_dataset/'
CONDITION_TRAIN = './datasets/condition_train/'
CONDITION_TEST = './datasets/condition_test/'
CONDITION_LABELS = './labels/condition_labels.txt'
CONDITION_MODELS = './models/classifiers/conditions/'
CONDITION_GANS = './models/gans/conditions/'